### ISSUE TITLE
Running BlazorForms without LDAP

### ISSUE THREAD

**Issue by hrybko** [MarvinKlein1508/BlazorForms#60]
Hi Marvin

I was excited to find your work on a Blazor based Form Designer.
Please can I ask if its possible to run and test without LDAP? 
I work in the Windows 11 environment with no access to LDAP servers and cannot get further without a login.

Is there anything you can suggest.

Thank you
Howard

**Comment by MarvinKlein1508** [comment]
Hi @hrybko 

BlazorForms can run both in LDAP and local mode.

To enable local mode open your `appsettings.json` and set
`ENABLE_LDAP_LOGIN` to `false` and `ENABLE_LOCAL_LOGIN` to `true`

Next you'll need to create a local admin user. Todo so navigate to the output folder of the project and open a command prompt. 

Type BlazorForms.exe -setup and choose option 1. 

Please note that this app is still in development and database structure etc. might change in future.

**Comment by hrybko** [comment]
Thank you Marvin!

*That worked 100%*

Really appreciate your help

Howard
Dr Howard Rybko
CEO
syncrony.com
*M * +27827778881
*P*  +27117836888
*E * ***@***.***
[image: Syncrony.com]

**Comment by MarvinKlein1508** [comment]
Hi @hrybko 

I've updated the README with proper installation instructions. Also I've added some missing localizations in recent commits. 

Feel free to open any issue for suggestions or any issues you may run into.
